// Package schemadoc extracts the config schema descriptions from the
// config package's doc comments, the way schemars reads Rust doc
// comments: a type's description is its doc after the first paragraph
// (the Go sentence naming the type, which revive requires), a field's
// is its whole doc, and an enum variant's is its constant's doc. The
// text is kept verbatim (markdown), one leading space stripped per
// line.
//
// Generate renders the result as schemadoc_gen.go; `go generate
// ./config` writes it and config's tests fail when it is stale.
package schemadoc

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// OutputName is the generated file's name inside the package dir.
const OutputName = "schemadoc_gen.go"

// Extract reads every non-test Go file of the package in dir and
// returns the description map: "Type" for types, "Type.Field" for
// struct fields, "Type=value" for string enum constants.
func Extract(dir string) (map[string]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	docs := map[string]string{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == OutputName {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch gd.Tok {
			case token.TYPE:
				extractTypes(gd, docs)
			case token.CONST:
				extractConsts(gd, docs)
			}
		}
	}
	return docs, nil
}

func extractTypes(gd *ast.GenDecl, docs map[string]string) {
	for _, spec := range gd.Specs {
		ts, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}
		doc := ts.Doc
		if doc == nil && len(gd.Specs) == 1 {
			doc = gd.Doc
		}
		if text := typeDescription(ts.Name.Name, commentText(doc)); text != "" {
			docs[ts.Name.Name] = text
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			continue
		}
		for _, field := range st.Fields.List {
			text := commentText(field.Doc)
			if text == "" {
				continue
			}
			for _, n := range field.Names {
				docs[ts.Name.Name+"."+n.Name] = text
			}
			if ident, ok := field.Type.(*ast.Ident); ok && len(field.Names) == 0 {
				// An embedded field is named after its type.
				docs[ts.Name.Name+"."+ident.Name] = text
			}
		}
	}
}

func extractConsts(gd *ast.GenDecl, docs map[string]string) {
	for _, spec := range gd.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		ident, ok := vs.Type.(*ast.Ident)
		if !ok || len(vs.Values) != 1 || vs.Doc == nil {
			continue
		}
		lit, ok := vs.Values[0].(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			continue
		}
		value, err := strconv.Unquote(lit.Value)
		if err != nil {
			continue
		}
		if text := commentText(vs.Doc); text != "" {
			docs[ident.Name+"="+value] = text
		}
	}
}

// commentText returns a comment group's lines verbatim, "//" and one
// following space removed, surrounding blank lines trimmed.
func commentText(g *ast.CommentGroup) string {
	if g == nil {
		return ""
	}
	lines := make([]string, 0, len(g.List))
	for _, c := range g.List {
		text := c.Text
		if !strings.HasPrefix(text, "//") {
			continue
		}
		text = strings.TrimPrefix(text, "//")
		text = strings.TrimPrefix(text, " ")
		if strings.HasPrefix(text, "nolint") || strings.HasPrefix(text, "go:") {
			continue
		}
		lines = append(lines, text)
	}
	return strings.Trim(strings.Join(lines, "\n"), "\n")
}

// typeDescription drops the Go-convention first paragraph ("Name is
// ...") and returns the rest.
func typeDescription(name, doc string) string {
	first, rest, _ := strings.Cut(doc, "\n\n")
	if strings.HasPrefix(first, name+" ") {
		return strings.Trim(rest, "\n")
	}
	return doc
}

// Generate renders the description map as the package's generated
// Go file.
func Generate(dir, pkg string) ([]byte, error) {
	docs, err := Extract(dir)
	if err != nil {
		return nil, err
	}
	keys := make([]string, 0, len(docs))
	for k := range docs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate (config/internal/schemadoc); DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// schemaDocs holds the schema descriptions extracted from the doc\n// comments: \"Type\", \"Type.Field\", and \"Type=variant\" keys.\n")
	b.WriteString("var schemaDocs = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(k), strconv.Quote(docs[k]))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
